- cmd/curio/run.go
- cmd/curio/tasks/tasks.go
- deps/deps.go
- go.mod
- go.sum
- harmony/harmonydb/sql/20240527-machine_name.sql
- web/hapi/simpleinfo.go
- web/hapi/web/cluster_machines.gohtml
- web/hapi/web/node_info.gohtml
- web/static/index.html
Add the friendly name to Curio node during start up.
> feat: add node name

- cmd/curio/proving.go
- cmd/curio/tasks/tasks.go
- tasks/seal/task_porep.go
- tasks/window/compute_task.go
- tasks/winning/winning_task.go
Small feature making my life much faster when testing with a calib node - basically now when starting a node with tasks which require tasks we'll start the node instantly, and paramfetch checks will run in the background. Tasks which compute snarks will be registered, but will not accept tasks until paramfetch is finished. Other tasks are allowed to run in the background though.
> Async paramfetch

- harmony/harmonydb/sql/20231217-sdr-pipeline.sql
- harmony/harmonydb/sql/20240529-sdr-pipeline-task-extract.sql
- web/api/webrpc/harmony_stats.go
- web/hapi/routes.go
- web/hapi/simpleinfo.go
- web/hapi/web/cluster_machines.gohtml
- web/hapi/web/sector_info.gohtml
- web/static/harmony-task-counts.mjs
- web/static/index.html
- web/static/pipeline_porep.html
This PR adds a table showing recent task history on the sector page (for tasks in the pipeline table, so really useful for debugging what caused the sector to halt progress) + Adds a "Resume" button on sectors which have tasks that have been retried too many times
The retry button removes failed taskIDs from the pipeline table so that the poller can start a new task in its place.
Tested on my setup, works as intended and looks coherent with the rest of the UI; Unfortunately I retried my failed sector before making this PR, so not much to share in the form of a screenshot.
> UI: Display active task history, retry sector button

- lib/ffiselect/ffiselect.go
It was broken due to missing gob binding
> fix WdPost through ffiselect

- web/api/webrpc/harmony_stats.go
- web/static/harmony-task-counts.mjs
- web/static/task/index.html
- web/static/task/task-history.mjs
- web/static/task/task-machines.mjs
- web/static/ux/curio-ux.mjs
Clickable from the tasks table on the main page; One page per task type detailing what's going on with that task in the cluster.
Mainly useful to see:
* Recent errors
* If any machine in the cluster is setup to handle the task type.
> UI: Add task deatails page

- cmd/curio/proving.go
- tasks/window/compute_do.go
- tasks/window/compute_task.go
- web/hapi/watch_actor.go
This PR:
* Fixes a race in WdPoSt generation code
* Fixes skipped sector handling in post verification
* Corrects handling of failing-to-verify WdPosts
> Fix wdpost skip / race issues

- market/fakelm/lmimpl.go
Occasionally seeing this in my curio logs
```
reflect.Value.Call
/home/magik6k/.opt/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/reflect/value.go:380
github.com/filecoin-project/lotus/metrics/proxy.proxy.func1
/home/magik6k/.opt/go/pkg/mod/github.com/filecoin-project/lotus@v1.27.0-rc1.0.20240527035155-18795706288e/metrics/proxy/proxy.go:69
github.com/filecoin-project/lotus/api.(*StorageMinerStruct).SectorsStatus
/home/magik6k/.opt/go/pkg/mod/github.com/filecoin-project/lotus@v1.27.0-rc1.0.20240527035155-18795706288e/api/proxy_gen.go:6984
reflect.Value.call
/home/magik6k/.opt/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.linux-amd64/src/reflect/value.go:596
```
> Fix occasional lmrpc SectorStatus panic

- apt/DEBIAN/control
- cmd/curio/main.go
- cmd/curio/tasks/tasks.go
- go.mod
- lib/fastparamfetch/paramfetch.go
This is a copy of https://github.com/filecoin-project/go-paramfetch/blob/master/paramfetch.go with:
* Heavily opinionated support for aria2
* Parallel fetch support
In the future we can think of adding support for p2p fetches from the cluster, but for now this makes my paramfetch operations 7-10x faster
> Paramfetch with aria2 support

- cmd/curio/ffi.go
- go.mod
- go.sum
- lib/ffi/sdr_funcs.go
- lib/ffiselect/ffidirect/ffi-direct.go
- lib/ffiselect/ffiselect.go
- lib/ffiselect/testffi.go
- tasks/window/compute_do.go
- tasks/winning/winning_task.go
Depends on https://github.com/filecoin-project/go-jsonrpc/pull/114
> Simplify ffiselect, fix winningPoSt

- cmd/curio/tasks/tasks.go
- harmony/harmonydb/sql/20231110-mining_tasks.sql
- harmony/harmonydb/sql/20240610-mining-inclusion-checks.sql
- tasks/winning/inclusion_check_task.go
- tasks/winning/winning_task.go
- web/api/webrpc/win_stats.go
- web/static/index.html
- web/static/win-stats.mjs
This PR:
* Makes WinnigPoSt work (a regression when ffiselect broke it in a subtle way)
* Adds a new task tracking inclusion of previously mined blocks
* Adds a table to the UI which shows stats for up to 8 recently won blocks
> Fix winning PoSt, track inclusion, display in webui

- cmd/curio/tasks/tasks.go
- tasks/winning/winning_task.go
Another regression from ffiselect, apparently made me loose 32 FIL on mainnet.
Not having this resulted in errors like
```
error: failed to compute winning post proof: get winning sector:6822,vanila failed: fsstat: path not found
```
> Fix WinningPoSt with remote sectors

- cmd/curio/guidedsetup/guidedsetup.go
Guided setup is now fixed
```
Defaulting to English. Please reach out to the Curio team if you would like to have additional language support.
✔ Create a new miner
┌────────────────────────────────────────────────────────────┐ 
│This interactive tool creates a new miner actor and creates │ 
│the basic configuration layer for it.                       │ 
└────────────────────────────────────────────────────────────┘ 
This process is partially idempotent. Once a new miner actor has been created and subsequent steps fail, the user need to run 'curio config new-cluster < miner ID >' to finish the configuration.
✔ Continue to connect and update schema.
✔ Step Complete: Pre-initialization steps complete
Initializing a new miner actor.
✔ Owner Wallet: <empty>
Enter the owner address: …
```
> fix: sector size in guided-setup

- cmd/curio/guidedsetup/shared.go
- harmony/harmonydb/sql/20240425-sector_meta.sql
- harmony/harmonydb/sql/20240612-deal-proposal.sql
- tasks/seal/task_submit_commit.go
- web/api/sector/sector.go
This PR does the following:
1. Expand sectors_meta_pieces to have f05_deal_proposal column
2. When migrating from miner, also copy over f05_deal_proposal
3. Sector UI now uses both sectors_meta_pieces and sectors_sdr_initial_pieces tables to put together the details
> fix: update piece metadata to get deal details

- lib/fastparamfetch/paramfetch.go
Apparently `-o` is relative to current dir, so we'd fetch into paths like `/home/magik6k/curio//var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk`
No idea how this seemed to work previously, but definitely seems to work now.
> Fix paramfetch dest dir with aria2

- lib/ffiselect/ffi_test.go
- lib/ffiselect/ffiselect.go
Change:
Whenever we see <2 GPUs, we just do a call locally. 
Reasoning: 
-  I'm unsure why we saw recursion, but this should resolve it because the subsequent depth will only see 1 GPU. 
- Performance improvement for machines with 1 card
- It implicitly supports the 0 GPU "dev-net" case.
> FFISelect improvements

- alertmanager/doc.go
- alertmanager/plugin/pager_duty.go
- alertmanager/plugin/plugin.go
- alertmanager/plugin/prometheus_alertmanager.go
- alertmanager/task_alert.go
- deps/config/doc_gen.go
- deps/config/types.go
- documentation/en/configuration/default-curio-configuration.md
https://github.com/filecoin-project/curio/discussions/83
Added support for the [Prometheus AlertManager](https://github.com/prometheus/alertmanager), resulting in a change to the configuration file format:
Previously:
```go
type CurioAlerting struct {
// PagerDutyEventURL is the URL for PagerDuty.com Events API v2. Events sent to this API URL are ultimately
// routed to a PagerDuty.com service and processed.
// The default is sufficient for integration with the stock commercial PagerDuty.com company's service.
PagerDutyEventURL string
// PageDutyIntegrationKey is the integration key for a PagerDuty.com service. You can find this unique service
// identifier on the integration page for the service.
PageDutyIntegrationKey string
// MinimumWalletBalance is the minimum balance for all active …
```
> feat: Add support for Prometheus AlertManager

- documentation/en/SUMMARY.md
- documentation/en/getting-started.md
- documentation/en/versions.md
Curio docs should include the expected versions of other related systems.
> doc: versions

- Makefile
Lets support as old has Haswell from 2013. 
This still unnecessarily blocks 2008-2012 chips like Via Nano, Bulldozer, etc, but those are likely more expensive to run & maintain than to replace. 
And v3 we get AVX & AVX2 which are often used in compiler optimizations. I know Go uses AVX to zero large ram allocations.
> no amd build opmz

- go.mod
- market/fakelm/lmimpl.go
Boost calls SectorsStatus to check if deals are in the sector, and it really likes to see the DealID there
Unfortunately Snap converts all deals to DDO, so to fix this the rpc adapter decodes the dealID back from the PAM
> lmrpc: Decode DDO in SectorsStatus

- market/fakelm/lmimpl.go
Fixes the second edge-case is SectorsStatus, where a sector which has just been committed and added to sectors_meta may not yet have it's prove message fully land on-chain
> fix SectorsStatus sector state edge-case

- tasks/window/compute_task.go
- web/api/webrpc/harmony_stats.go
Stop using broken YB function string_to_array()
> no string-to-array

- harmony/harmonydb/sql/20240611-snap-pipeline.sql
- harmony/harmonydb/sql/20240809-snap-failures.sql
- market/deal_ingest_seal.go
- market/deal_ingest_snap.go
- tasks/seal/poller_commit_msg.go
- tasks/seal/task_submit_commit.go
- tasks/snap/task_submit.go
- web/api/webrpc/upgrade.go
- web/static/snap/upgrade-sectors.mjs
Should address all concerns from https://github.com/filecoin-project/curio/issues/104
Definitely fixes sector selection logic.
> Fix Sector selection in snap ingester

- market/deal_ingest_snap.go
- tasks/snap/finalize_pieces.go
- tasks/snap/task_encode.go
- web/api/webrpc/upgrade.go
- web/static/snap/upgrade-sectors.mjs
* Add a delete button for failed sectors in the snap pipeline page
* Cleanup piece refs after encode in SnapDeals (this is where we finalize), this was leaving piece files around
* Make snap sector selection if there isn't already active snap for candidate sectors
Last one was causing
```
2024-08-12T17:24:00.412+0200	WARN	rpc	go-jsonrpc@v0.5.1-0.20240730181539-2bb4fbb48fdd/handler.go:474	error in RPC call to 'Filecoin.SectorAddPieceToAny': allocating sector numbers:
github.com/filecoin-project/curio/market.(*PieceIngesterSnap).AllocatePieceToSector
/home/magik6k/curio/market/deal_ingest_snap.go:372
- adding deal to sector:
github.com/filecoin-project/curio/market.(*PieceIngesterSnap).AllocatePieceToSector.func1
/home/magik6k/curio/market/deal_ingest_snap.go:364
- ERROR: Conflict detected …
```
> Fix: improve snap piece cleanup / selection

- web/static/chain-connectivity.mjs
The ok status was this overflowing alert widget for quite some time, looked really ugly, so made it better.
> webui: Fix chain connectivity status display

- tasks/message/watch.go
There is zero reason to not allow repricing messages.
> message: Allow repriced messages

- web/api/sector/sector.go
- web/static/sector/index.html
> fix: invalid sp in the sector list page

- harmony/harmonydb/sql/20240824-longterm-indexes.sql
* Mining base lookups were the 3rd most time-consuming query in my stats, due to the winnnigPoSt task looking up the mining base by task_id which wasn't indexed
* Message waits are updated by joining waits with non-null waiter machine to message sends on signed cid. Because neither column had an index each invocation would trigger an insanely expensive sequential of both tables on every epoch, making it the second most expensive query.
Most time-consuming is
```
SELECT id 
FROM harmony_task
WHERE owner_id IS NULL AND name=$1
ORDER BY update_time
```
But this one is expensive purely because it's executed very frequently, the execution itself seems to be very cheap with avg time at ~8ms on my cluster; Also does basically no IO since it's all going to be in memory due to that table being …
> Add indexes to mining and message waits tables

- market/fakelm/lmimpl.go
Afaict the query behavior is exactly the same, it just uses 2 more CTE to guide postgres to use the correct indexes
> lmrpc: Avoid table scans in SectorsStatus

- market/fakelm/lmimpl.go
- market/lmrpc/lmrpc.go
Apparently after the sectors was snapped and got an update to sectors_meta it would perpetually claim to be in UpdateReplica, just beginning to get snapped
> lmrpc: Fix snap Proving state

- web/api/webrpc/pipeline_porep.go
- web/api/webrpc/sector.go
- web/static/pages/node_info/node-info.mjs
- web/static/pages/pipeline_porep/index.html
- web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
- web/static/pages/pipeline_porep/restart-all-button.mjs
> webui: Show task fails and allow bulk restart on PoRep page

- cmd/curio/rpc/rpc.go
- go.mod
- web/devsrv/main.go
- web/srv.go
Added an API proxy to make it possible to develop web UI without running a local Curio node.
To run:
- set the `CURIO_API_SRV` env variable to a node web UI address
- `go run ./web/devsrv/main.go`
> Feat: Add api proxy dev server

- tasks/metadata/task_sector_expirations.go
This should make initial indexing much faster and much more robust
> Batch deadline setting in SectorMetadata

- tasks/winning/winning_task.go
This PR adds some more defense-in-depth measures to the winning code, it should now be utterly impossible to get slashed, even doing weirdest combos of node restarts.
> winpost: Add more defenses against slashing

- tasks/seal/poller_commit_msg.go
- tasks/seal/poller_precommit_msg.go
- tasks/snap/task_submit.go
Apparently there are two ways in which messages can fail with out-of-funds
This PR adds a retry for the second way.
Note that if the sender is still out of funds the immediate retry will still likely fail, but on gas estimation, without sending the message, but after that the sector will be in a retry-able state
Also added logic for sending retry in snapdeals pipeline
> seal/snap: Handle insufficient funds errors correctly

- Makefile
- deps/config/doc_gen.go
- deps/config/types.go
- documentation/en/configuration/default-curio-configuration.md
- go.mod
- harmony/harmonydb/harmonydb.go
- harmony/harmonydb/sql/20240731-market-migration.sql
- harmony/harmonydb/sql/20240823-ipni.sql
- harmony/harmonydb/userfuncs.go
- market/indexstore/indexstore.go
- market/ipni/chunker/chunker.go
- market/ipni/chunker/initial-chunker.go
- market/ipni/ipni-provider/ipni-provider.go
- market/ipni/ipniculib/ipniculib.go
- tasks/indexing/task_ipni.go
* Change IPNI entry creation to be dependent on number of blocks in a piece
* Below 500k entries per piece (64kb block in 32G) read from DB
* Above 500k re-create entries by doing range car-reads
* No caches involved anymore, entries get recreated on the fly, with low latency
* Switched entries from dag-json to dag-cbor, apparently IPNI shouldn't care much, and in the future this will make it easy to switch to the much, much faster cbor-gen for entry creation.
* Ads remain as dag-json
> feat: Simpler IPNI

- Makefile
Apparently the comment was breaking it
> fix: cuda library path setting

- harmony/harmonytask/harmonytask.go
- harmony/taskhelp/max.go
- tasks/seal/task_sdr.go
- tasks/unseal/task_unseal_sdr.go
This was the problem - we use ActiveThis to account for hardware resources - https://github.com/filecoin-project/curio/blob/baad9d01d5480c69a5df64a452b77033cebeb799/harmony/harmonytask/harmonytask.go#L432-L431 - and if a This counter was shared between two tasks (e.g. SDR / unseal-SDR), we'd see each task take double the resources
> fix: harmony: Correctly separate this counters when sharing Max

- web/api/webrpc/sector.go
- web/static/pages/sector/sector-info.mjs
Fixes https://github.com/filecoin-project/curio/issues/247
> feat: restart button for sectors

- Makefile
- tasks/unseal/task_unseal_decode.go
- web/api/webrpc/pipeline_porep.go
- web/api/webrpc/tasks.go
- web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
Fixes https://github.com/filecoin-project/curio/issues/185
Table sorted with Running tasks and then pending tasks. Both of them are then ordered by Posted Time.
Different color for waiting tasks
> fix: show task waiting in PoRep pipeline

- cmd/curio/guidedsetup/shared.go
Fixes https://github.com/filecoin-project/curio/issues/224
> fix: multiple api keys found in the database when migrating multiple miner IDs

- alertmanager/alerts.go
Fixes https://github.com/filecoin-project/curio/issues/129
This PR fixes some issues with how alerts were generated for wdPost and wnPost.
> fix: alerts for wnPost and wdPost

- cmd/sptool/sector.go
- web/api/sector/sector.go
We should be using PowerBaseEpoch instead of SectorActivation to calculate power for sectors. 
PowerBaseEpoch == SectorActivation when sector is activated.
> fix: sector list power after extension

- cmd/curio/guidedsetup/guidedsetup.go
- cmd/curio/market.go
- cuhttp/server.go
- harmony/harmonydb/sql/20240731-market-migration.sql
- lib/cachedreader/cachedreader.go
- lib/dealdata/urlpiecereader.go
- market/ipni/chunker/initial-chunker.go
- market/ipni/ipni-provider/ipni-provider.go
- market/retrieval/retrieval.go
- tasks/indexing/task_indexing.go
- tasks/indexing/task_ipni.go
- tasks/storage-market/storage_market.go
Fixes for a couple random issues encountered when testing PDP
> market: Backport fixes from the PDP branch

- tasks/message/watch.go
Early return can choke the cluster if first message results in the error. We should should log the error and try the next one.
> fix: do not return early from message watcher

- tasks/window/compute_do.go
Fixes a regression introduced in https://github.com/filecoin-project/curio/pull/252
Below we call `postPartition.Skipped`, which internally will try to write to an uninitialized map
> fix: post: create skipped bitfield to avoid panics with faults

- market/deal_ingest_snap.go
`maxExpiration` checks were added after the initial testing, and somehow until now no one noticed that snap doesn't work with non-filplus deals.
Not setting that value meant that we were looking for sectors expiring
> fix: snap: Correctly handle non-filplus deals

- tasks/sealsupra/task_supraseal.go
Without this batch tasks would be added when CanAccept would refuse them.
Normally this wouldn't be much of an issue, but if there are batch machines in the cluster capable of different batch sizes, one could "take" all unbatched sectors from the other machine.
This PR makes it so that batches are only created when needed.
> fix: sealsupra: Only schedule when needed

- Makefile
- lib/ffi/cunative/decode_sdr.go
- lib/ffi/cunative/decode_snap.go
- lib/ffi/cunative/decode_snap_test.go
- lib/ffi/cunative/decode_test.go
- lib/ffi/cunative/nonative.go
This makes it possible to use curio as a library again.
Context: https://filecoinproject.slack.com/archives/C06GD1SS56Y/p1727193366887699
> cunative: Only pull in native deps with a tag

- harmony/resources/getGPU.go
- lib/ffiselect/ffiselect.go
This PR adds a new env-var knob, `HARMONY_GPU_OVERPROVISION_FACTOR`, which when set to values >1 will make each "GPU" present itself as N GPUs.
For example when set to 2 on a snap encode worker, each GPU will handle two independent encode processes at once. TBD if this makes sense. Note that snark workloads will probably struggle with memory on non-enterprise GPUs.
> experiment: GPU Overprovisioning

- deps/apiinfo.go
- web/api/webrpc/sync_state.go
Fixes https://github.com/filecoin-project/curio/issues/243 and https://github.com/filecoin-project/curio/issues/200
This PR bring in the changes from https://github.com/filecoin-project/lotus/pull/11470 along with addressing some comments. 
This PR also removes the forced check to ensure at least 2 chain nodes are reachable. We don't require this check as there is no network segregation or split-brain issues here. Any node will work as long as it is in sync. This check also has some unintended affects of rendering Curio cluster useless if a node goes down out of 2.
> fix: Improved multinode proxy

- cmd/curio/tasks/tasks.go
- harmony/harmonydb/sql/20241017-market-mig-indexing.sql
- tasks/gc/pipeline_meta_gc.go
- tasks/indexing/task_indexing.go
- tasks/indexing/task_ipni.go
- tasks/storage-market/storage_market.go
This PR makes the following changes to the market migration.
1. The indexing tasks are no longer created directly.
2. All info is captured in a table `market_mk12_deal_pipeline_migration`
3. A migration function is called every 30 seconds by market poller to migrate data from this table to mk12_pipeline table which in turn creates indexing tasks along with IPNI if required.
4. The function has following logic:
- Step 1: Check if the migration table has entries
- Step 2: Count entries ready for indexing in the pipeline table
- Step 3: Count pending IPNI tasks
- Calculate how many entries we need to reach 16
- Calculate how many entries we can move without exceeding 16 pending IPNI tasks
- Limit by the number of entries available in the migration table
- Move entries from the migration …
> controlled indexing after migration

- cmd/curio/guidedsetup/shared.go
Also adds a simple progress print every 1000 sectors.
> Use transactions in sector migrations

- web/static/config/edit.html
- web/static/pages/config/list/config-list.mjs
- web/static/pages/config/list/index.html
- web/static/ux/curio-ux.mjs
Fixes https://github.com/filecoin-project/curio/issues/283
The configuration save cookie has not been functioning for a while. This PR fixes it.
> fix: config save cookie

- tasks/f3/f3_task.go
If we keep going here, we'll panic. See (also includes a regression test):
https://github.com/filecoin-project/lotus/pull/12634
> fix(f3): handle failure to receive manifest from the client

- pdp/handlers.go
- pdp/handlers_upload.go
This enables a service using PDP to query based on its upload parameters and poll for upload completion. The primary requirement is this should only return a piece cid if there is a retrievable piece for the given parameters.
- Add an provides an endpoint to look up a piece cid for a given set of upload parameters. It will only respond if the piece exists. It will also mark if the piece is retriavable and whether it's ready for PDP aggregation. This largely mimics some initial logic from POST /pdp/piece that determines if it's 201 created (new upload) or 200 (existing upload)
- Add docs for new endpoint
- Correct one comment that appears to refer to the wrong table.
Currently, this will succeed as soon as the piece finishes uploading, and it will seperately note if the piece is …
> feat(pdp): add endpoint to poll for completed upload

- go.mod
- tasks/f3/f3_task.go
Ports the fix from https://github.com/filecoin-project/lotus/pull/12640 to curio.
> f3: Update participate loop to always participate

- harmony/harmonydb/sql/20241030-deal-label.sql
- market/libp2p/libp2p.go
- market/mk12/mk12.go
- tasks/storage-market/storage_market.go
- tasks/storage-market/task_find_deal.go
- tasks/storage-market/task_psd.go
We save the label as bytes outside of the proposal and then read the same each time we need proposal. Proposal in sector_metadata and pipeline will still be missing this label but we don't really care about that as Label is only useful for market process.
> fix: deal label storage in DB

- go.mod
- go.sum
lotus-rc2 miss-registered error types, rc3 does it correctly
Next release will additionally contain fix for early reneweal. https://github.com/filecoin-project/lotus/pull/12667 but that is Lotus side only
https://github.com/filecoin-project/curio/issues/312 is still an issue
> Fix F3 participation erroring out on sentinel errors

- harmony/harmonydb/sql/20240731-market-migration.sql
- harmony/harmonydb/sql/20240823-ipni.sql
- harmony/harmonydb/sql/20241029-mk12-filters.sql
- harmony/harmonydb/sql/20241104-piece-info.sql
- tasks/indexing/task_indexing.go
- web/api/webrpc/market.go
- web/static/pages/market/index.html
- web/static/pages/market/market-balance.mjs
- web/static/pages/market/piece-summary.mjs
- web/static/ux/curio-ux.mjs
> piece summary page

- pdp/auth.go
fix annoying bug - x509 does not parse to pointer type on ed25519
From the doc on x509.ParsePKIXPublicKey
```golang
// ParsePKIXPublicKey parses a public key in PKIX, ASN.1 DER form. The encoded
// public key is a SubjectPublicKeyInfo structure (see RFC 5280, Section 4.1).
//
// It returns a *[rsa.PublicKey], *[dsa.PublicKey], *[ecdsa.PublicKey],
// [ed25519.PublicKey] (not a pointer), or *[ecdh.PublicKey] (for X25519).
// More types might be supported in the future.
//
// This kind of key is commonly encoded in PEM blocks of type "PUBLIC KEY".
```
> fix(pdp): fix ed25519 auth

- lib/supraffi/common.go
- lib/supraffi/no_supraseal.go
- lib/supraffi/seal.go
- tasks/sealsupra/metrics.go
- tasks/sealsupra/task_supraseal.go
This PR makes curio output logs like
```
2024-11-10T19:37:18.734Z	INFO	batchseal	sealsupra/task_supraseal.go:128	nvme health page	{"hp": [{"CriticalWarning":0,"Temperature":32,"TemperatureSensors..
```
Eventually that should go to e.g. /metrics/pprof, but for now logs are better than nothing at all
Full example output:
```
{
"hp": [
{
"CriticalWarning": 0,
"Temperature": 31, // pretty sure this is C
"TemperatureSensors": [
31,
43,
-273,
-273,
-273,
-273,
-273,
-273
],
"WarningTempTime": 0,
"CriticalTempTime": 0,
"AvailableSpare": 100,
"AvailableSpareThreshold": 10,
"PercentageUsed": 0,
"DataUnitsRead": 7351772500, // 512B blocks? (maybe 4k? idk, maybe it depends, tho probably just 512B)
"DataUnitsWritten": 194806471,
"HostReadCommands": 918971519654, // cumulative iops …
```
> wip: Supraseal healthpage output

- documentation/en/installation.md
The Golang versio  should be at-least the one specified in the repo's minimum file.
> Doc: go version

- Makefile
Likely a regression from https://github.com/filecoin-project/curio/pull/211
> fix: Pass correct tags to sptool calibnet build

- harmony/harmonydb/metrics.go
- lib/paths/local.go
- lib/paths/metrics.go
Output in the /metrics endpoint looks like
```
curio_curio_stor_generate_single_vanilla_proof_duration_seconds_bucket{cache_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",sealed_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",update="false",le="0.1"} 0
curio_curio_stor_generate_single_vanilla_proof_duration_seconds_bucket{cache_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",sealed_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",update="false",le="1"} 0
curio_curio_stor_generate_single_vanilla_proof_duration_seconds_bucket{cache_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",sealed_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",update="false",le="5"} 6
curio_curio_stor_generate_single_vanilla_proof_duration_seconds_bucket{cache_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",sealed_id="a18b0ebe-7177-42f1-aa73-81869e822d8d",upda …
```
> storage: Add post challenge reading metrics

- cmd/curio/tasks/tasks.go
- deps/config/doc_gen.go
- deps/config/types.go
- deps/deps.go
- documentation/en/configuration/default-curio-configuration.md
- harmony/harmonydb/sql/20231217-sdr-pipeline.sql
- harmony/harmonydb/sql/20240611-snap-pipeline.sql
- harmony/harmonydb/sql/20241210-sdr-batching.sql
- itests/curio_test.go
- tasks/seal/poller.go
- tasks/seal/poller_commit_msg.go
- tasks/seal/poller_precommit_msg.go
- tasks/seal/task_porep.go
- tasks/seal/task_submit_commit.go
- tasks/seal/task_submit_precommit.go
- tasks/seal/task_treerc.go
- tasks/snap/task_submit.go
Pre/proof/upgrade commit Messages batching.
> feat: batching

- web/static/cluster-tasks.mjs
This PR adds a mode to the Cluster Tasks viewer where "similar" tasks are grouped together.
"Similar" means a matching SPID, Task Name and Owner
Without Coalesce:
With:
> feat: webui: Coalesce cluster tasks

- web/static/pages/task/id/index.html
- web/static/pages/task/id/task-status.mjs
Was really missing a way to just individually restart tasks. Mostly useful when debugging edge-cases, but also helpful when cleaning up after unclean node shutdowns.
> feat: webui: Task restart button

- lib/ffi/sdr_funcs.go
- tasks/seal/task_finalize.go
- tasks/seal/task_synth_proofs.go
This PR makes the following changes:
1. Generating Unsealed is now a separate function called GenerateUnsealedSector()
2. This function is called by Synthetic Task if required and generating the unsealed sector before removing the cache.
3. Finalize calls generating unseal only if proof types is not synthetic.
4. Acquiring sector from Storage is still done by the primary function in each task as passed to GenerateUnsealedSector().
> fix: unsealed sector for synthetic PoRep

- Dockerfile
- Makefile
- docker/docker-compose.yaml
- web/api/webrpc/market.go
- web/api/webrpc/pipeline_porep.go
- web/api/webrpc/sector.go
- web/static/pages/mk12-deal/deal.mjs
- web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
- web/static/pages/sector/sector-info.mjs
- web/static/snap/upgrade-sectors.mjs
> Improve sector UI page

- api/api_curio.go
- api/proxy_gen.go
- api/types/types.go
- build/openrpc/curio.json
- cmd/curio/cli.go
- cmd/curio/cordon.go
- cmd/curio/info.go
- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/messages.gotext.json
- cmd/curio/internal/translations/locales/zh/messages.gotext.json
- cmd/curio/rpc/rpc.go
- documentation/en/api.md
- documentation/en/curio-cli/curio.md
- harmony/harmonydb/sql/20250111-machine-maintenance.sql
- harmony/harmonytask/harmonytask.go
- scripts/docgen/docgen.go
- web/api/webrpc/cluster.go
- web/static/cluster-machines.mjs
- web/static/pages/node_info/node-info.mjs
- Add `unschedulable` field to harmony_machines
- Implement cordon operation to mark node as unschedulable 
- Implement uncordon operation to resume node scheduling
https://filecoinproject.slack.com/archives/C06GD1SS56Y/p1736216228423539
> feat: add node scheduling control

- deps/apiinfo.go
- web/api/webrpc/storage_stats.go
- web/static/gc/gc-marks.mjs
- web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
Without pagination, we end up with page refusing to load where GC number is large.
> add pagination to storageGC page

- cuhttp/server.go
ACME protocol is misconfigured so lets encrypt fails on new cert requests.  See this thread: https://filecoinproject.slack.com/archives/C0717TGU7V2/p1738321145982859
> Fix acme challenge

- alertmanager/alerts.go
This should fix the math for winningPoSt alerts, making them not fire all the time for no reason
> fix: WinPoSt alert

- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/messages.gotext.json
- cmd/curio/internal/translations/locales/zh/messages.gotext.json
- cmd/curio/test-cli.go
- deps/deps.go
- documentation/en/curio-cli/curio.md
- tasks/gc/storage_gc_mark.go
- web/api/webrpc/sector.go
- web/static/gc/gc-marks.mjs
This PR adds additional marking logic to GC Mark task for cleaning up non-needed post-snap sector key files (original CC sector files):
Sectors where:
* `sectors_meta` table indicates a snap sector (orig_unsealed_cid != cur_sealed_cid)
* On-chain sector info is not null (1.5 finality ago)
* On-chain sector info has a non-nil SectorKeyCID indicating the sector is a snap sector
* On disk, the `update` and `update-cache` files are present for the sector, indicating that PoSt logic won't use the sealed file
* Have the sealed file on disk
Will have the sealed file (only) marked for GC
> feat: gc: Mark snap sector key files for removal

- deps/config/doc_gen.go
- deps/config/types.go
- documentation/en/configuration/default-curio-configuration.md
- tasks/storage-market/storage_market.go
PieceLocator expects 2 different endpoints right now for piece info and data. This PR now merges them into one and expects HEAD and GET requests to correctly send the requested data/metadata.
> fix: combine piecelocator endpoints

- documentation/en/supraseal.md
The instructions were a little upside down, the order now is now much easier to follow when setting up a new machine
> docs: Improve supraseal setup docs

- deps/deps.go
- deps/deps_test.go
Fixes https://github.com/filecoin-project/curio/issues/368
> keep base layer updated with new config

- .circleci/config.yml
- Dockerfile
- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/messages.gotext.json
- cmd/curio/internal/translations/locales/zh/messages.gotext.json
- cmd/curio/market.go
- cmd/sptool/evm.go
- cmd/sptool/toolbox_deal_client.go
- cmd/sptool/toolbox_deal_tools.go
- docker/piece-server/entrypoint.sh
- docker/piece-server/sample/ddo-deal.sh
- docker/piece-server/sample/make-a-deal.sh
- documentation/en/curio-cli/curio.md
- documentation/en/curio-cli/sptool.md
- harmony/harmonydb/sql/20240731-market-migration.sql
- harmony/harmonydb/sql/20250220-mk12-ddo.sql
- harmony/harmonydb/sql/mk12-ddo.sql
- harmony/harmonytask/singleton_task.go
- market/ipni/ipni-provider/ipni-provider.go
- tasks/indexing/task_indexing.go
- tasks/storage-market/storage_market.go
- tasks/storage-market/task_commp.go
- web/api/webrpc/market.go
- web/static/pages/mk12-deals/index.html
- web/static/pages/mk12-deals/mk12-deals.mjs
- web/static/pages/mk12-deals/mk12ddo-list.mjs
- web/static/pages/piece/piece-info.mjs
- A new command to add DDO deals to table and pipeline
- A new column in market_mk12_deal_pipeline to identify the DDO deal
- Small changes in mk12 pipeline to accomodate DDO deals
- UI changes for DDO
- Some small fixes to deal pipeline
> feat: offline verified ddo deals

- web/api/webrpc/market.go
- web/static/pages/mk12-deals/mk12-deals.mjs
- web/static/pages/mk12-deals/mk12ddo-list.mjs
- web/static/ux/yesno.mjs
This PR fixes the deal removal button. It was broken after DDO deals.
It also fixes the Deal list to correctly say processed instead of Stored and displayed the error
> fix: deal removal and list

- cmd/curio/rpc/rpc.go
This PR adds a Prometheus HTTP Service Discovery endpoint, which allows Prometheus to dynamically discover and scrape Curio nodes in the network.
Implements a new HTTP handler at `/debug/service-discovery` that returns a JSON list of targets in [Prometheus SD format](https://prometheus.io/docs/prometheus/latest/http_sd/)
Add the following job to your Prometheus configuration:
```
- job_name: 'curio'
metrics_path: 'debug/metrics'
http_sd_configs:
- url: 'http://your-curio-node:port/debug/service-discovery'
```
This feature has been tested in my development environment and is working properly.
> Add Prometheus service discovery endpoint

- api/api_curio.go
- api/proxy_gen.go
- build/openrpc/curio.json
- cmd/curio/cli.go
- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/messages.gotext.json
- cmd/curio/internal/translations/locales/zh/messages.gotext.json
- cmd/curio/rpc/rpc.go
- documentation/en/api.md
- documentation/en/curio-cli/curio.md
The PR adds a new `cli` command to Curio. It fetches some random CIDs from the indexed piece for any sampling needs.
```
remote node version: [1 24 5]
Multihash HEX                                                         Multihash B58                                   CID v1                                                       
1220bb5ec163482b437a04097f4ace29e0d90a5844ddb0ec3e378679b4177e0d13bd  Qmax4kXGccJUUMMQ4X7KaZGEQLvcgaJxdyxg3wttGcXtEY  bafybeif3l3awgsblin5aicl7jlhctygzbjmejxnq5q7dpbtzwqlx4ditxu  
1220f0891135e2eae25ef88ffae3b303c4112d81c9820c6dc53136be65c226382221  QmeXbnC1h3t5VWgP6aL2nsVfEZDHcGjysgh8ohqgW8u5Ep  bafybeihqreitlyxk4jpprd724ozqhrarfwa4taqmnxctcnv6mxbcmobcee  
```
```
root@0a2a48a645e9:/app# curio cli --machine 172.20.0.4:12300 index-sample --json …
```
> feat: index sample command

- .circleci/config.yml
- Makefile
- cmd/curio/config_test.go
- cmd/curio/tasks/tasks.go
- cmd/sptool/toolbox_deal_tools.go
- deps/config/common.go
- deps/config/doc_gen.go
- deps/config/load.go
- deps/config/old_lotus_miner.go
- deps/config/types.go
- documentation/en/configuration/default-curio-configuration.md
- documentation/en/curio-market/deal-filters.md
- itests/curio_test.go
- lib/testutils/testutils.go
- market/indexstore/indexstore_test.go
- market/storageingest/deal_ingest_seal.go
- market/storageingest/deal_ingest_snap.go
- tasks/seal/poller.go
- tasks/snap/task_submit.go
- tasks/storage-market/storage_market.go
- web/api/apihelper/apihelper.go
- web/api/config/config.go
- web/static/config/edit.html
- web/static/pages/market-settings/defaults.mjs
This PR does the following:
1. Dump custom Duration type for TOML as time.Duration is supported by TOML by default now.
2. Removed unused configuration
3. Fix commenting for sections
4. Fix commenting for [Arrays]
5. Small UI and doc fix
```
#
[Subsystems]
```
```
#
[Market]
#
[Market.StorageMarketConfig]
#
[Market.StorageMarketConfig.MK12]
```
```
#
[[Addresses]]
#
#PreCommitControl = []
#
#CommitControl = []
#
#DealPublishControl = []
```
> fix: Update config comment with expected input and defaults

- tasks/sealsupra/supra_config.go
Previous code made incorrect assumption on how hashers behave, after this fix it's possible to run supraseal in single-hasher mode.
> fix: Correct supra single hasher core assignments

- harmony/harmonydb/sql/20241028-padding.sql
- harmony/harmonydb/sql/20250310-fix-ingest.sql
- tasks/seal/poller_commit_msg.go
- tasks/snap/task_submit.go
This PR does following:
1. Move the CommitLanded and UpdateLanded into a DB transaction.
2. Replace ingest seal now SQL functions to fix below error:
```
2025-03-10 16:00:52 2025-03-10T12:00:52.076Z    ERROR   storage-ingest  storageingest/deal_ingest_seal.go:172   start sealing sector: adding sector to pipeline: ERROR: duplicate key value violates unique constraint "open_sector_pieces_pkey" (SQLSTATE 23505)
```
> fix: mark deal sealed in a DB transaction

- apt/DEBIAN/postinst
- cmd/curio/guidedsetup/guidedsetup.go
- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/messages.gotext.json
- cmd/curio/internal/translations/locales/zh/messages.gotext.json
- cmd/curio/main.go
- deps/deps.go
- documentation/en/curio-cli/curio.md
- documentation/en/curio-service.md
- documentation/en/installation.md
- harmony/harmonydb/harmonydb.go
- itests/curio_test.go
- market/indexstore/indexstore.go
- market/indexstore/indexstore_test.go
- web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
Changes:
1. Remove CURIO_DB statements from error. They at best confuse the user when actually would be something else. 
2. Remove CURIO_DB as a viable env variable. Again due to chaos this var causes
3. Use Postgres URI instead of DSN to allow connecting to all hosts from get code with load_balance enabled
4. Update the content of post migrate env file
5. Add details to CLI flags related to DB. Add the same to docs
6. Add a new flag to Cassandra port
> update curio cli flags

- harmony/harmonydb/sql/20231217-sdr-pipeline.sql
- harmony/harmonydb/sql/20250312-batching-functions.sql
- tasks/seal/poller.go
- tasks/seal/poller_commit_msg.go
- tasks/seal/poller_precommit_msg.go
This PR moved the batch creation logic from Go to SQL for preCommit and Commit messages.
Tested Following:
> SQL based batch creation

- alertmanager/alerts.go
- cmd/curio/config.go
- cmd/curio/config_test.go
- cmd/curio/guidedsetup/guidedsetup.go
- cmd/curio/guidedsetup/shared.go
- cmd/curio/tasks/tasks.go
- deps/config/doc_gen.go
- deps/config/load.go
- deps/config/types.go
- deps/deps.go
- documentation/en/SUMMARY.md
- documentation/en/configuration/balance-manager.md
- documentation/en/configuration/default-curio-configuration.md
- documentation/en/curio-market/ipni-interplanetary-network-indexer-provider.md
- documentation/en/curio-market/storage-market.md
- tasks/storage-market/market_balance.go
- web/api/webrpc/sync_state.go
This PR adds a new task which can automatically top off the miner's market balance. This balance is used for deal collateral.
> feat: Balance Manager

- .github/image/Dockerfile
- Dockerfile
- Makefile
- harmony/harmonytask/harmonytask.go
- itests/curio_test.go
- lib/paths/http_handler.go
- lib/paths/local.go
- tasks/message/sender.go
- tasks/piece/task_park_piece.go
- tasks/seal/poller_commit_msg.go
- tasks/seal/poller_precommit_msg.go
- tasks/seal/task_porep.go
- tasks/seal/task_submit_precommit.go
This PR mostly have small fixes.
1. Fix Commit and Precommit batch condition
2. Update StartEpoch poller condition
3. Improve storage logging
4. Improve seal poller logging
5. Drops TestCurioNewActor from itest. We already cover this in TestCurioHappyPath
6. Improves the harmonyTak retry logic.
> fix: store log debug, seal poller log, batching, itest

- tasks/indexing/task_check_indexes.go
It was observed that IPNI tasks were being executed for deals which were not indexed. In Curio, we treat this as no go. Both fast_retrieval and announce_to_ipni must be true for deal to be indexed. Otherwise, we will announce a deal which cannot be retrieved due to missing local indexes. 
This PR fixes the condition to check which deals should be consider for repairing IPNI.
> fix: phantom IPNI tasks

- market/storageingest/deal_ingest_seal.go
Fixed the nil panic issue that occurs when using ddo, where accessing piece.DealProposal leads to a null pointer dereference.
> Fix panic in allocateToExisting

- harmony/harmonydb/sql/20241105-walletnames.sql
- web/api/webrpc/market_filters.go
- web/api/webrpc/wallet.go
- web/static/lib/cu-wallet.mjs
- web/static/pages/actor/actor-detail.mjs
- web/static/pages/actor/index.html
- web/static/pages/ipni/ipni_status.mjs
- web/static/pages/market-settings/allow-list.mjs
- web/static/pages/market-settings/client-filters.mjs
- web/static/pages/market-settings/defaults.mjs
- web/static/pages/market-settings/index.html
- web/static/pages/market-settings/pricing-filters.mjs
- web/static/pages/market/index.html
- web/static/pages/market/market-balance.mjs
- web/static/pages/mk12-deal/deal.mjs
- web/static/pages/mk12-deal/index.html
- web/static/pages/wallet/index.html
- web/static/pages/wallet/wallet.mjs
- web/static/ux/curio-ux.mjs
This is more of a sketch since I haven't tested it. 
I know some UI @LexLuthr  was working on had a need to show many wallets. I think he could use this.
> wallet friendly names

- pdp/contract/addresses.go
I ignored the nice build flag stuff earlier, now curio will work with correct contract immediately -- nice
> Do the correct thing

- Makefile
- documentation/en/supraseal.md
This PR separates the `sptool` build from `make batch` and updates the documentation for the same.
> fix: batch build

- Makefile
Users installing Curio for PDP-only operations do not need to have CUDA libraries installed.
Running `sudo make install` without CUDA libraries installed results in the following error:
```
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
install -C ./curio /usr/local/bin/curio
install -C ./sptool /usr/local/bin/sptool
```
Tested with `curio version 1.25.0+mainnet+git_90cd136_2025-04-14T12:54:07-04:00`
> Update Makefile for Non-CUDA Installs

- cmd/pdptool/main.go
- pdp/handlers.go
The `PDPVerifier` contract allows passing an opaque byte array as "extradata" that gets passed to the listener as is. This is needed for allowing the client/provider to pass in payer/payee addresses and proofset/root metadata to the listener to build payment flows/better explorer UX.
> feat: allow clients to pass extra-data for proof set creation and adding roots

- .gitignore
- Makefile
Fixes https://github.com/filecoin-project/curio/issues/475
```
% make pdptool
rm -f pdptool
go build  -tags "cunative" -o pdptool ./cmd/pdptool
% ./pdptool -v
pdptool version 1.25.0+mainnet
```
> make pdptool

- market/retrieval/piecehandler.go
1. Allows malicious builders to use PDP provider has host to malicious content
2. If malicious script is flagged, PDP provider's domain will be hit
3. Locking down CORS will mean external builders cannot serve directly from PDP provider
4. How do we find a balance? Where do we draw the line?
Added server side sniffing and only do "inline" if a valid MIME type is detected. This handles the security risks upto some degree.
> pdp browser rendering

- cmd/curio/config_test.go
- cmd/curio/tasks/tasks.go
- deps/config/load.go
- docker/curio/entrypoint.sh
- harmony/harmonydb/sql/20250423-remove-fee-aggregation.sql
- itests/curio_test.go
- tasks/seal/poller.go
- tasks/seal/poller_commit_msg.go
- tasks/seal/poller_precommit_msg.go
- tasks/seal/task_submit_commit.go
fixes https://github.com/filecoin-project/curio/issues/489
Should not break nodes running older code during upgrade
> no fee based aggregation/batching

- market/mk12/mk12.go
PDP changed the constraint, which was fine in markets then, but pdp took so long on its branch that half of markets were rewritten in that time, so it wasn't updated.
> fix piecepark conflict spec in deal ingest

- pdp/auth.go
- pdp/handlers.go
- pdp/handlers_upload.go
Refactor pdp service to take alternate athentication and implement null authentication
> ServiceAuth and NullAuth

- cuhttp/server.go
Can't access `Location` header from within a browser context and we need it for PDP uploads.
> chore(cors): expose Location header to JS for PDP

- pdp/handlers_upload.go
Also from the `synapse` branch. A bugfix that prevented "findPiece" from finding pieces, it was not looking in the right table.
> fix(pdp): look in pdp piecerefs to check for actual readiness

- harmony/harmonydb/sql/20250113-pdp-never-delete.sql
- pdp/handlers.go
- tasks/pdp/proofset_addroot_watch.go
- Add `Location` header to root addition response with tx hash
- Add `GET /proof-sets/{id}/roots/added/{txHash}` endpoint for status checks
- Implement `handleGetProofSetRoot` for retrieving root details
- Return confirmed root IDs after transaction confirmation
- **Use lowercase transaction hashes consistently in database operations**
> feat(pdp): add transaction tracking for root additions (synapse branch)

- extern/supraseal/README.md
The SPDK commit [017f65b](https://github.com/spdk/spdk/commit/017f65b5f153f2c2e80798fa09f25d052523578e) promotes spdk_nvme_identify from the examples/ directory to app/, changing its install location to build/bin/spdk_nvme_identify
> docs: update README to use correct SPDK identify binary path

- web/api/webrpc/storage_stats.go
- web/static/pages/sector/sector-info.mjs
There's a bug in the RPC when there was a GC mark on a path which was removed (e.g. failed drive) the page wouldn't render - which was because left join caused `sl.can_store` to be null, which then we tried to scan into `bool` which obviously failed.
> fix gc page with missing paths

- cmd/curio/tasks/tasks.go
- harmony/harmonydb/sql/20250727-balancemgr.sql
- tasks/balancemgr/task_balancemgr.go
- web/api/webrpc/balance_manager.go
- web/static/pages/wallet/balance-manager.mjs
- web/static/pages/wallet/index.html
- web/static/pages/wallet/messages.mjs
- web/static/pages/wallet/wallet.mjs
- web/static/ux/message.mjs
Small weekend project, and massive quality of life improvement when managing too many wallets.
Initially intended to have this be a part of the snark market PR, where it is pretty nice for auto-withdrawing market income from a separate wallet into a main one, but this got a little big, and also is entirely independent, soo here is.
This PR:
* Adds a new "balance manager" feature
* Automatically send from wallet A to B when B is BELOW some balance
* Automatically send from wallet A to B when B is ABOVE some balance
* In both cases bounds are set as Low/High watermark to limit frequency of message sends
* Also:
* Cleans up the wallet page quite a bit, adding some more info to it
* Improves the Message component, adding more complete, possible to copy on-hover info
* Small UX tweaks here and …
> Wallet Balance Manager

- cmd/pdptool/main.go
- Add getJWTTokenForService() wrapper that returns empty token for 'public' service
- Update all commands to use the wrapper instead of direct JWT creation
- Only set Authorization header when JWT token is not empty
- Allows pdptool to work with public services without requiring pdpservice.json
Fixes #558
> fix(pdptool): Skip JWT auth for public service

- cmd/curio/tasks/tasks.go
- deps/config/doc_gen.go
- deps/config/types.go
- documentation/en/configuration/default-curio-configuration.md
- tasks/message/sender.go
There is generally no reason not to set MaximizeFeeCap on message send spec. We somehow didn't have a config for this all this time, so this PR fixes that.
This setting just sets basefee limit - it doesn't touch gas premium - so all messages are always sent with maximum FeeCap we're willing to pay, which is much better than the lotus default of 'up to 10x current network basefee rate' that's guaranteed to get messages stuck in the mempool when there is any sort of congestion.
> feat: config for maximized feecap

- pdp/contract/addresses.go
- pdp/handlers.go
- pdp/handlers_upload.go
- tasks/pdp/task_init_pp.go
- tasks/pdp/task_next_pp.go
- tasks/pdp/task_prove.go
Not sure why I encountered the errant `== sql.ErrNoRows` on the rename branch, maybe a fluke, but I've done a search and replace of all instances of ErrNoRows checking in the PDP code and am using errors.Is and pgx.ErrNoRows.
> pdp (rename): use errors.Is(err, pgx.ErrNoRows)

- cmd/curio/debug-proofsvc.go
- lib/proofsvc/clientctl.go
- tasks/proofshare/task_client_poll.go
Needs to propagate through a context because of the use of the retryWithBackoff helper.
> fix: yield in PSClientPoll correctly

- tasks/gc/storage_gc_mark.go
We were basically comparing apples to oranges. Every sector was considered as snapped - this was still mostly safe as for correct files to be removed there was still the separate check that update files existed, but this would have caused us to mark too many files for GC in some scenarios.
> fix gc mark snapdeal sector query

- lib/proofsvc/clientctl.go
- tasks/proofshare/task_client_poll.go
- tasks/proofshare/task_client_upload.go
Those logs don't really say anything useful and are extreeeemely spammy, GBs per day.
> fix proofshare log spam

- pdp/contract/addresses.go
- pdp/handlers.go
This provides some protection for curio PDP operators running publically accessible PDP services.  Only the pandora PDP service contract is allowed upon proofset creation over the publically available PDP service.  
The whitelist is network dependent -- only calibnet specified as pandora only launched on calibnet.
Closes https://github.com/FilOzone/synapse-sdk/issues/34
> PDP service contract whitelist

- README.md
Curio participates in the Flow ecosystem via **Flow EVM (Chain ID 747)**.
This enables contributors to use Flow EVM endpoints and receive rewards through the ReWTF program.
Flow EVM RPC configuration:
- **RPC URL:** https://mainnet.evm.nodes.onflow.org
- **Chain ID:** 747
- **Currency Symbol:** FLOW
- **Block Explorer:** https://evm.flowscan.io/
> add flow EVM Integration

- web/srv.go
Enables cross-origin requests by adding CORS headers and handling preflight OPTIONS requests.
> Add CORS middleware to web server

- alertmanager/alerts.go
Fix for https://github.com/filecoin-project/curio/issues/603
It appears that over-eager reporting is causing false negatives. Reporting on the previous will solve that with a minimal loss of timeliness.
> Alert on older-than-head failures

- tasks/indexing/task_indexing.go
The changes are based on below definition. Most deals are carV1 so we never hit this till now.
```
BlockMetadata contains metadata about a block's section in a CAR file/stream.
There are two offsets for the block section which will be the same if the original CAR is a CARv1, but will differ if the original CAR is a CARv2.
The block section offset is position where the CAR section begins; that is, the begining of the length prefix (varint) prior to the CID and the block data. Reading the varint at the offset will give the length of the rest of the section (CID+data).
In the case of a CARv2, SourceOffset will be the offset from the beginning of the file/steam, and Offset will be the offset from the beginning of the CARv1 payload container within the CARv2.
Offset is useful for index …
```
> fix: use SourceOffset to support CarV2

- cmd/curio/internal/translations/catalog.go
- cmd/curio/internal/translations/locales/en/out.gotext.json
- cmd/curio/internal/translations/locales/ko/out.gotext.json
- cmd/curio/internal/translations/locales/zh/out.gotext.json
- cmd/curio/test-cli.go
- documentation/en/curio-cli/curio.md
- lib/proof/post_vproof_verify.go
- tasks/window/compute_do.go
We had a pure-Go vanilla PoSt proof verifier for a while now, that never got used. Wrapped it into a tool to debug particularly confusing PoSt failures of the `failed to generate window post`+ no other information flavor.
This tool will show which specific vanilla proofs contained errors which for whatever reason don't get checked on the rust side until the actual proof is computed.
```
GOLOG_LOG_LEVEL=error ./curio-cu test wd vanilla --addr f0... --deadline 1
2025-10-06T12:20:53.913+0200	ERROR	main	curio/test-cli.go:499	Verified window post vanilla proofs	{"error": "comm_r invalid: sector 3245, partition 0", "elapsed": 0.001823394, "ok": false}
2025-10-06T12:20:54.168+0200	ERROR	main	curio/test-cli.go:499	Verified window post vanilla proofs	{"error": "comm_r invalid: sector 4567, …
```
> feat: test post cli: Vanilla Proof test command

- tasks/proofshare/task_client_send.go
- web/static/pages/proofshare/proofshare-client.mjs
Currently setting up as a client in Snark Market apparently doesn't work very well due to a few regressions, this PR fixes the onboarding flow:
* UI wasn't able to create client entries because address can't be null
* Even if the client entry was manually inserted into the database, the refactored payment logic wasn't capable of creating a payment with nonce=0
* Also wasn't possible to remove client entries from the UI
> fix: Snark Market: Unbrick client setup

- pdp/handlers.go
A valid extraData needs to be provided by the client for FWSS to allow
PDP to delete the data.
> feat(pdp): handle extraData in handleDeleteDataSetPiece
