Dockerfile
apt/DEBIAN/changelog
apt/DEBIAN/control
apt/DEBIAN/copyright
apt/DEBIAN/postinst
apt/curio.service
apt/make_debs.go

This PR also changes the name "Lotus" to "Curio" wherever required.

fix: port over debian from Lotus

---

web/hapi/simpleinfo.go

Tested with MinerX. This fixes the UI issue.

fix node name in UI

---

deps/deps.go

fix: set listen address when supplied

---

apt/DEBIAN/postinst
documentation/en/curio-service.md

Also adds FIL_PROOFS_USE_MULTICORE_SDR=1 to ENV file

fix: create log directory

---

web/api/webrpc/tasks.go
web/static/cluster-tasks.mjs

It got broken with the changes in https://github.com/filecoin-project/curio/pull/79 / https://github.com/filecoin-project/curio/pull/85

fix cluster tasks UI

---

market/fakelm/lmimpl.go

Current query was not taking sector_meta table into account. This can lead to Boost thinking sealing failed incorrectly.

fix: sector status output

---

tasks/seal/task_sdr.go
tasks/winning/winning_task.go
web/api/webrpc/tasks.go
web/static/cluster-tasks.mjs

Makes the Cluster Tasks SP ID display actually work this time

SpID getter fixes

---

alertmanager/alerts.go

Fixes #107 
This PR modifies AlertManager to check all control addresses for each miner on chain along with their worker address to generate low fund alert.

fix: add control addresses from chain

---

cmd/sptool/actor.go

This subcommand seems to be calling harmonyDB to get Full node. This should not be used. `sptool` is independent of Curio and control list is fetched from chain. There is no need to get FullNode from harmonyDB. We can use local ENV var to set it up.

fix: sptool control list command

---

.circleci/config.yml
Dockerfile
build/params_testnet.go
cmd/curio/config_new.go
cmd/curio/test-cli.go
docker/curio/entrypoint.sh

This PR does the following:
1. Fix wdPost output strings
2. Fix broken new-cluster command
3. Add test for debug, calibnet, 2k builds
4. Improve docker devnet

fix: broken commands

---

web/static/pages/sector/sector-info.mjs

fix: sector detail page

---

web/api/webrpc/sector.go
web/static/pages/sector/sector-info.mjs

Was broken in the hapi refactor

Fix the resume button in sector info UI

---

web/api/webrpc/cluster.go
web/static/cluster-machines.mjs
web/static/pages/node_info/node-info.mjs

This PR:
* Adds a layer list to the node page
* Makes the node page refresh data every 2.5s
* Adds links in machine summary

webui: Config layers on node page

---

go.mod
go.sum
web/srv.go

web debug fix

---

web/api/webrpc/harmony_stats.go
web/static/task/index.html
web/static/task/task-history.mjs

Basically a duplicate of the first table but not showing recent successes (which are generally less interesting)

webui: Always show recent task fails in the task page

---

harmony/harmonydb/sql/20240425-sector_meta.sql
harmony/harmonydb/sql/20240611-snap-pipeline.sql
harmony/harmonydb/sql/20240826-sector-partition.sql
lib/curiochain/epoch.go
market/deal_ingest_seal.go
market/deal_ingest_snap.go
market/lmrpc/lmrpc.go
tasks/metadata/task_sector_expirations.go
tasks/snap/task_submit.go

Make Snap sector picker deadline-aware

---

documentation/en/design/harmony-tasks.md

Update Resource table

---

web/api/webrpc/cluster.go
web/static/cluster-machines.mjs

Fixes https://github.com/filecoin-project/curio/issues/127

feat: node uptime in UI

---

web/api/webrpc/pipeline_porep.go

Fixes https://github.com/filecoin-project/curio/issues/245

fix: PoRep count in PoRep summary

---

web/static/win-stats.mjs

Fixes https://github.com/filecoin-project/curio/issues/244

fix: allow copying the block cid from winning stats table

---

Makefile
build/params_2k.go
harmony/resources/getGPU_darwin.go

Fixes a regression from https://github.com/filecoin-project/curio/pull/211 and darwin build regression from https://github.com/filecoin-project/curio/pull/262

fix make calibnet

---

cmd/curio/market.go
documentation/en/curio-cli/curio.md
web/api/webrpc/market.go
web/static/pages/market/index.html
web/static/pages/market/market-balance.mjs

Add MoveEscrow to UI

---

pdp/auth.go

Allows accepting JWTs that are signed with Ed25519 as well as ECDSA

feat(pdp): add ed25519 support for JWT

---

FUNDING.json

This sets up https://filecoin.drips.network

chore: RPGF2 Setup

---

cmd/curio/guidedsetup/shared.go

Fixes https://github.com/filecoin-project/curio/issues/341

fix: multiple storage secret

---

build/openrpc/curio.json
build/version.go
documentation/en/curio-cli/curio.md
documentation/en/curio-cli/sptool.md

chore: release v1.24.3

---

tasks/seal/poller_commit_msg.go
tasks/seal/poller_precommit_msg.go
tasks/snap/task_submit.go
web/api/webrpc/pipeline_porep.go
web/api/webrpc/upgrade.go
web/static/lib/dateutil.mjs
web/static/pages/pipeline_porep/pipeline-porep-sectors.mjs
web/static/snap/upgrade-sectors.mjs

Hopefully the last batch of batching fixes, tested on my setup, it does appear to work much better now.
Also includes some improvements to the Snap/Porep pages

fix: Some more batching fixes

---

web/api/webrpc/sector.go

Small fix to support the "don't change" state

fix: Fix unseal status on the sector page

---

build/openrpc/curio.json
build/version.go
documentation/en/curio-cli/curio.md
documentation/en/curio-cli/sptool.md

release: v1.24.4

---

web/api/webrpc/actor_charts.go
web/api/webrpc/actor_summary.go
web/static/pages/actor/actor-detail.mjs

- "Address" should be correctly string-serialized
- Font on the charts is super tiny compared to other things (adjustable now)
- BeneficiaryTerm value is gray on gray, can barely see the text (CSS issue, fixed)
- The labels on Y axis in the charts could be nicer (e.g. say value in X FIL instead of nnExx attofil) - Fil and QAP are displayed in human friendly way now.

fix: actor info page issues

---

tasks/seal/poller_commit_msg.go
tasks/seal/poller_precommit_msg.go

This should fix a race condition when there are multiple pollers running and a batch message was sent.

fix: Don't rechedule batch sends

---

deps/apiinfo.go

Related to https://github.com/filecoin-project/curio/pull/379, but just making calibnet nodes possible to start

fix: Calibnet startup

---

tasks/seal/poller_commit_msg.go
tasks/seal/poller_precommit_msg.go

https://github.com/filecoin-project/curio/blob/d7ff21c0f4567b743dd16c9b48c8f9f6d19a4bbc/tasks/seal/task_submit_precommit.go#L329-L331

fix: seal: Check the correct column before assigning batch submit task

---

lib/ffi/sdr_funcs.go

Fixes the issue where unsealed path is not detected correctly by Finalize ensureOne() function.

fix: finalize ensureOne

---

cmd/curio/tasks/tasks.go
deps/config/doc_gen.go
deps/config/types.go
documentation/en/configuration/default-curio-configuration.md
tasks/seal/task_treed.go
tasks/unseal/task_unseal_decode.go

feat: option to bind TreeD to SDR node

---

web/api/webrpc/sector.go
web/static/config/edit.html
web/static/gc/index.html
web/static/index.html
web/static/pages/actor/index.html
web/static/pages/config/list/index.html
web/static/pages/ipni/index.html
web/static/pages/market-settings/index.html
web/static/pages/market/index.html
web/static/pages/mk12-deal/index.html
web/static/pages/mk12-deals/index.html
web/static/pages/node_info/index.html
web/static/pages/piece/index.html
web/static/pages/pipeline_porep/index.html
web/static/pages/sector/index.html
web/static/pages/task/id/index.html
web/static/pages/task/index.html
web/static/sector/index.html
web/static/snap/index.html
web/static/ux/components/Drawer.mjs
web/static/ux/curio-ux.mjs

menu drawer

---

documentation/en/SUMMARY.md
documentation/en/curio-pdp.md
documentation/en/experimental-features/Enable-PDP.md

All credits to: @ZenGround0 for writing the docs. These are just porting these over to the correct repo from https://github.com/filecoin-project/curio-docs/pull/2

feat: add Curio PDP docs

---

cmd/curio/internal/translations/catalog.go
cmd/curio/internal/translations/locales/en/out.gotext.json
cmd/curio/internal/translations/locales/ko/messages.gotext.json
cmd/curio/internal/translations/locales/zh/messages.gotext.json
cmd/curio/main.go
deps/config/old_lotus_miner.go
deps/deps.go
documentation/en/curio-cli/curio.md
harmony/harmonydb/harmonydb.go

This is to avoid error when working with containerized YB. Load balancer uses the IP where YB is running even we provide a service IP to connect with Postgres.

make postgres load balance optional

---

market/mk12/cidgravity.go

- Add missing `DealTransferType` value to CIDgravity payload

feat: add transfer type to cidgravity payload

---

web/api/webrpc/actor_summary.go

fix UI wallet name on actor detail page

---

harmony/harmonydb/sql/20240529-sdr-pipeline-task-extract.sql
harmony/harmonydb/sql/20240611-snap-pipeline.sql
harmony/harmonydb/sql/20250331-fix-bulk-restart-func.sql

The bulk restart fail on snap function with error `failed to resume SnapDeals sector: ERROR: FOREACH expression must not be null (SQLSTATE 22004)`

fix: bulk pipeline restart

---

.github/image/Dockerfile
.github/utils/create-runner-image.sh
.github/utils/setup.md
Makefile
web/static/ux/curio-ux.mjs

- Update lotus version for devnet images
- Undo menu drawer, there are some glitches that we need to fix
- Update Github Action files

update lotus version for devnet, undo menu drawer

---

deps/deps.go
pdp/contract/addresses.go

Just updating some addresses.  Merging this one quick.

Mainnet api and pdp addr

---

deps/deps.go

Using build tags as with the contract address

Connect to correct api for network

---

cuhttp/server.go

this applies to _all_ http, so includes /piece/ but also lets you do things from the browser on /pdp/

feat: cors headers on http endpoint

---

tasks/pdp/task_prove.go

This way you can have multiple different keys owning different proofsets

Get owner key for proofset from chain

---

tasks/pdp/task_init_pp.go
tasks/pdp/task_next_pp.go

Add maximum retries logic to PDP tasks

Add maximum retries logic to PDP tasks

---

alertmanager/alerts.go
alertmanager/task_alert.go

Fixes https://github.com/filecoin-project/curio/issues/187

alert for missing sectors

---

cmd/curio/internal/translations/catalog.go
cmd/curio/internal/translations/locales/en/out.gotext.json
cmd/curio/internal/translations/locales/ko/messages.gotext.json
cmd/curio/internal/translations/locales/zh/messages.gotext.json
cmd/curio/main.go
cmd/curio/toolbox.go
documentation/en/curio-cli/curio.md

Creating a new `toolbox` under Curio is a choice to keep `sptool` separated from Curio's DB.

tool to update msg watcher from FilFox if required

---

deps/apiinfo.go
deps/deps.go

use full node for eth client

---

pdp/handlers.go
tasks/pdp/notify_task.go
tasks/piece/task_park_piece.go

Addresses synapse issue https://github.com/FilOzone/synapse-sdk/issues/81 though not a clean and complete fix. For that we'll want to do some postgres LISTEN NOTIFY stuff as explained in the linked issue.

Tighter busy waiting

---

documentation/en/SUMMARY.md
documentation/en/experimental-features/Snark-Market.md

Snark Market Provider Docs - Experimental

Snark Market Provider Setup (not client)

---

market/mk12/mk12.go
market/storageingest/deal_ingest_seal.go
market/storageingest/deal_ingest_snap.go

Fixes https://github.com/filecoin-project/curio/issues/550

fix: allow less than 1 MiB verified deal

---

pdp/handlers.go

When there are no roots in a proof set we don't yet have a `prove_at_epoch` so we need to gracefully handle that case.
Current code does:
500 Internal Server Error - Failed to retrieve next challenge epoch: can't scan into dest[0]: cannot scan NULL into *int64

fix(pdp): GET /pdp/proof-sets/{id} - handle uninitialised proof sets

---

web/api/webrpc/cluster.go
web/static/cluster-machines.mjs

CLI is nice for bulk/automated management, tho occasional access in the UI will be nice too

feat: Node cordon button in the UI

---

cmd/curio/tasks/tasks.go
deps/config/doc_gen.go
deps/config/types.go
deps/stats/wallet_exporter.go
documentation/en/configuration/default-curio-configuration.md
lib/ffi/piece_funcs.go
lib/ffi/scrub_funcs.go
lib/ffi/sdr_funcs.go
lib/ffi/snap_funcs.go
lib/ffi/task_storage.go
lib/ffi/unseal_funcs.go
tasks/sealsupra/task_supraseal.go

This PR has some fixes:
* Mainly includes https://github.com/filecoin-project/curio/pull/327 except proven in a real environment for a few days
* Fixes few big wallet exporter bugs
* Adds missing docstring to RemoteProofMaxUploads config

fix wallet exporter, supra allocs, config doc

---

tasks/pdp/task_prove.go

@Kubuxu 's fix, confirmed working.

fix(pdp): calculateProofFee ABI problem (rename branch)

---

pdp/contract/ListenerServiceWithViewContract.abi
pdp/contract/ListenerServiceWithViewContract.go
pdp/contract/utils.go
tasks/pdp/proofset_create_watch.go
tasks/pdp/task_init_pp.go
tasks/pdp/task_next_pp.go

Treat it as indirection to the contract that we can use to find a contract that implements IPDPProvingSchedule that we can use for proving parameters.

feat(pdp): handle case where PDP listener has a viewContractAddress

---

pdp/handlers.go

Fixes: https://github.com/filecoin-project/curio/issues/650

fix: group by piece_id when calculating PieceCIDv2 for piece list

---

tasks/balancemgr/handlers_f05.go
tasks/balancemgr/task_balancemgr.go
web/api/webrpc/balance_manager.go
web/static/pages/wallet/balance-manager.mjs

This PR adds balance manager integration for f05.
It's a little redundant with the config based one, but this one is configured with the UI and much more dynamic.

feat: f05 balance manager
